# Site settings
title: "Mad Lime"
email: madeline@hackartscience.com
description: > # ignore newlines
  OMERGAH FOOD.
baseurl: ""
url: "http://madlime.hackartscience.com"
facebook_username: madlime

# Build settings
markdown: kramdown
