# Site settings
title: madeline
email: madeline@hackartscience.com
description: > # ignore newlines
  A personal and professional site for Madeline Liou, a publishing
  consultant based in Boston.
baseurl: ""
url: "http://madlime.hackartscience.com"
twitter_username: madelineismadeline
facebook_username: madlime

# Build settings
markdown: kramdown
